language: r
cache: packages

# Add all CRAN versions of package you used here:
r_packages:
  - tidyverse
  - here
  - fivethirtyeight

# Add all GitHub versions of packages you used here:
r_github_packages:
  - moderndive/moderndive


# You do not need to change anything below this line:

# This UNIX command changes file mode to executable +x i.e. make a bash script
before_script:
  - chmod +x ./_build.sh
# Run the bash script.
script:
  - ./_build.sh
